[general]
library_name = "libaws_c_common"
output_file_path = "../src/lib.jl"
jll_pkg_name = "aws_c_common_jll"
smart_de_anonymize = true
extract_c_comment_style = "doxygen"
print_using_CEnum = true
use_julia_native_enum_type = false
print_enum_as_integer = false
use_deterministic_symbol = true
output_ignorelist = [
    "AWS_RESTRICT",
    "AWS_THREAD_LOCAL",
    "SIZE_MAX_POWER_OF_TWO",
    "AWS_COMMON_MATH_API",
    "AWS_THREAD_ONCE_STATIC_INIT",
    "AWS_BUS_ADDRESS_ALL",
]
auto_mutability = false
auto_mutability_with_new = false
show_c_function_prototype = true

[codegen]
use_julia_bool = true
use_ccall_macro = true
opaque_func_arg_as_PtrCvoid = true