name: Generate Bindings
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/generate_bindings.yml
      - gen/Project.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate-bindings:
    name: Generate bindings
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.10.2"

      - uses: julia-actions/cache@v2

      - name: Run the generator
        run: ./gen/generate.sh

      - name: Check for changes
        id: check_diff
        run: |
          if git diff --quiet; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Regenerate bindings"
          git push origin ${{ github.event.pull_request.head.ref }}